input_path: "./worldover-img"
output_path: "./worldover-landscape"
width: 5616
height: 3744
image_size_kb: 80
video_size_kb: 5000
video_format: "webm"
conversion_timeout: 60000
# Memory management settings
max_batch_size: 5  # Process only 5 files at a time
max_workers: 1     # Use only 1 worker to prevent memory issues