<<<<<<< HEAD
input_path: "./luminous"
output_path: "./luminous-img"
width: 2880
height: 4522
image_size_kb: 80
=======
input_path: "./profile"
output_path: "./corina-david"
width: 1024
height: 1024
image_size_kb: 70
>>>>>>> origin/main
video_size_kb: 5000
video_format: "mp4"
conversion_timeout: 60000